"""add recurring expenses model

Revision ID: 0cb794f8fed1
Revises: 575ebcbfe17f
Create Date: 2026-07-14 21:44:31.616753

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0cb794f8fed1'
down_revision: Union[str, Sequence[str], None] = '575ebcbfe17f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('recurring_expenses',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('group_id', sa.UUID(), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=False),
    sa.Column('payer_id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('total_amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('split_type', sa.String(length=20), nullable=False),
    sa.Column('frequency', sa.String(length=20), nullable=False),
    sa.Column('next_run_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False, server_default=sa.text('true')),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("frequency in ('daily', 'weekly', 'monthly')", name='chk_recurring_expenses_frequency'),
    sa.CheckConstraint("split_type in ('equal', 'exact', 'percentage')", name='chk_recurring_expenses_split_type'),
    sa.CheckConstraint('total_amount > 0', name='chk_recurring_expenses_total_amount'),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['group_id'], ['groups.id'], ),
    sa.ForeignKeyConstraint(['payer_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_recurring_expenses_created_by'), 'recurring_expenses', ['created_by'], unique=False)
    op.create_index(op.f('ix_recurring_expenses_group_id'), 'recurring_expenses', ['group_id'], unique=False)
    op.create_index(op.f('ix_recurring_expenses_payer_id'), 'recurring_expenses', ['payer_id'], unique=False)
    op.create_table('recurring_expense_splits',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('recurring_expense_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('amount_owed', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('amount_owed > 0', name='chk_recurring_expense_splits_positive'),
    sa.ForeignKeyConstraint(['recurring_expense_id'], ['recurring_expenses.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'recurring_expense_id', name='uniq_recurring_expense_splits_user')
    )
    op.create_index(op.f('ix_recurring_expense_splits_recurring_expense_id'), 'recurring_expense_splits', ['recurring_expense_id'], unique=False)
    op.create_index(op.f('ix_recurring_expense_splits_user_id'), 'recurring_expense_splits', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_recurring_expense_splits_user_id'), table_name='recurring_expense_splits')
    op.drop_index(op.f('ix_recurring_expense_splits_recurring_expense_id'), table_name='recurring_expense_splits')
    op.drop_table('recurring_expense_splits')
    op.drop_index(op.f('ix_recurring_expenses_payer_id'), table_name='recurring_expenses')
    op.drop_index(op.f('ix_recurring_expenses_group_id'), table_name='recurring_expenses')
    op.drop_index(op.f('ix_recurring_expenses_created_by'), table_name='recurring_expenses')
    op.drop_table('recurring_expenses')
    # ### end Alembic commands ###
