"""allow percentage expense split type

Revision ID: 2a01ef358964
Revises: c5cee85b94b6
Create Date: 2026-05-12 15:19:10.649495

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2a01ef358964'
down_revision: Union[str, Sequence[str], None] = 'c5cee85b94b6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('chk_expenses_split_type', 'expenses', type_='check',)
    op.create_check_constraint('chk_expenses_split_type', 'expenses', "split_type IN ('equal','exact','percentage')",)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('chk_expenses_split_type', 'expenses', type_='check',)
    op.create_check_constraint('chk_expenses_split_type', 'expenses', "split_type IN ('equal', 'exact')", )
    # ### end Alembic commands ###
