"""add settlement ownership

Revision ID: a51f6cce45e9
Revises: 2a01ef358964
Create Date: 2026-05-26 17:03:48.602912

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a51f6cce45e9'
down_revision: Union[str, Sequence[str], None] = '2a01ef358964'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('settlements', sa.Column('created_by', sa.UUID(), nullable=True))
    op.execute('UPDATE settlements SET created_by = payer_id WHERE created_by IS NULL')
    op.alter_column('settlements', 'created_by', existing_type=sa.UUID(), nullable=False)
    op.create_index(op.f('ix_settlements_created_by'), 'settlements', ['created_by'], unique=False)
    op.create_foreign_key('fk_settlements_created_by', 'settlements', 'users', ['created_by'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_settlements_created_by', 'settlements', type_='foreignkey')
    op.drop_index(op.f('ix_settlements_created_by'), table_name='settlements')
    op.drop_column('settlements', 'created_by')
    # ### end Alembic commands ###
