"""allow exact expense split type

Revision ID: c5cee85b94b6
Revises: 781ba9ca7cc0
Create Date: 2026-05-10 15:57:27.986097

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c5cee85b94b6'
down_revision: Union[str, Sequence[str], None] = '781ba9ca7cc0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('chk_expenses_split_type', 'expenses', type_='check',)

    op.create_check_constraint('chk_expenses_split_type', 'expenses', "split_type IN ('equal', 'exact')",)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('chk_expenses_split_type', 'expenses', type_='check',)
    op.create_check_constraint('chk_expenses_split_type', 'expenses', "split_type IN ('equal')")
    # ### end Alembic commands ###
