"""add cascade delete to expense splits

Revision ID: f0c1f3edc399
Revises: a51f6cce45e9
Create Date: 2026-07-01 12:50:43.193218

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f0c1f3edc399'
down_revision: Union[str, Sequence[str], None] = 'a51f6cce45e9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('expense_splits_expense_id_fkey'), 'expense_splits', type_='foreignkey')
    op.create_foreign_key('expense_splits_expense_id_fkey', 'expense_splits', 'expenses', ['expense_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('expense_splits_expense_id_fkey', 'expense_splits', type_='foreignkey')
    op.create_foreign_key(op.f('expense_splits_expense_id_fkey'), 'expense_splits', 'expenses', ['expense_id'], ['id'])
    # ### end Alembic commands ###
